# fly.toml app configuration file generated for fleet-telemetry on 2025-04-07T11:41:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fleet-telemetry'
primary_region = 'cdg'

[build]

[[services]]
  internal_port = 443
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
